import Navbar from "@/components/Navbar";
import Footer from "@/sections/Footer";
import GlobalQuoteSection from "@/sections/GlobalQuoteSection";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { useHeroViewportFit } from "@/hooks/use-hero-viewport-fit";
import { ArrowRight, Eye, ShieldCheck, Sun } from "lucide-react";

const benefits = [
  { title: "Advanced Monitoring", description: "Track system performance with intuitive monitoring platforms that provide real-time insights into energy production", icon: Eye },
  { title: "Performance Optimization", description: "System architecture designed to reduce losses from shading and improve overall energy consistency", icon: Sun },
  { title: "Built-In Safety Standards", description: "Code-compliant rapid shutdown and integrated protection features designed for modern residential systems", icon: ShieldCheck },
];

const fitScenarios = [
  {
    title: "Complex Roof Layouts",
    description: "Multiple planes, offsets, or obstructions may call for more adaptable inverter configurations",
    image: "/assets/microinverters/complex-roof-layouts.webp",
  },
  {
    title: "Variable Shading Conditions",
    description: "Partial or shifting shade can influence system architecture and monitoring strategy",
    image: "/assets/microinverters/variable-shading-conditions.webp",
  },
];

const faqs = [
  {
    q: "What does an inverter do in a solar system?",
    a: "An inverter converts the electricity generated by your panels into usable power for your home. It also manages system performance, monitoring, and safety functions.",
  },
  {
    q: "What’s the difference between string and microinverter systems?",
    a: "String systems convert power centrally, while module-level systems manage performance at each panel. The right choice depends on roof layout, shading, monitoring needs, and future plans.",
  },
  {
    q: "How does shading affect inverter selection?",
    a: "Shading can impact system performance depending on architecture. We evaluate roof conditions and recommend configurations that maintain consistent output.",
  },
  {
    q: "Can I monitor my system’s performance?",
    a: "Yes. All recommended systems include digital monitoring so you can track performance through a web or mobile app.",
  },
  {
    q: "How does inverter selection impact future battery expansion?",
    a: "Yes. Inverter architecture influences storage compatibility and expansion flexibility. We account for future upgrades during system design.",
  },
  {
    q: "Which inverter configuration is right for my home?",
    a: "There’s no one-size-fits-all answer. We assess roof complexity, shading, electrical setup, and long-term goals before recommending a configuration.",
  },
];

const Microinverters = () => {
  const { heroMediaStyle, heroOverlayStyle } = useHeroViewportFit();

  return (
    <main className="mobile-premium page-microinverters min-h-screen bg-[#f4eefb]">
      <Navbar />

      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="mobile-hero-media relative min-h-[460px] w-full" style={heroMediaStyle}>
          <img src="/assets/microinverters/microinverters-header-image.jpg" alt="Microinverter system hero visual." className="h-full w-full object-cover object-center" />
          <div className="absolute inset-0 bg-gradient-to-r from-[#17141b]/80 via-[#17141b]/46 to-[#17141b]/20" />
          <div className="absolute inset-0 mx-auto flex max-w-[1400px] items-center px-6 sm:px-8" style={heroOverlayStyle}>
            <div className="max-w-4xl text-white">
              <p className="mb-5 text-xs font-semibold uppercase tracking-[0.18em] text-white/80">INVERTERS</p>
              <h1 className="max-w-[980px] text-5xl font-medium leading-[0.98] tracking-tight text-white drop-shadow-[0_6px_24px_rgba(0,0,0,0.55)] sm:text-6xl lg:text-[82px]">
                Engineered for Performance. Built for Reliability.
              </h1>
              <p className="mt-7 max-w-[980px] text-[23px] font-medium leading-[1.34] text-white/82">
                The control center of your solar system. We select the right architecture to maximize efficiency, monitoring, safety, and scalability.
              </p>
              <a
                href="#contact"
                className="mt-10 inline-flex items-center gap-2 rounded-full bg-white px-7 py-3 text-sm font-semibold uppercase tracking-[0.14em] text-[#231f2a] transition-colors hover:bg-gray-200"
              >
                GET A QUOTE
                <ArrowRight className="h-4 w-4" />
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* Benefits — Icon strip with large image below */}
      <section className="py-16 sm:py-24">
        <div className="mx-auto max-w-[1400px] px-6 sm:px-8">
          <div className="mb-10 max-w-2xl">
            <p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-stone-500">POWER CONVERSION</p>
            <h2 className=" text-4xl text-stone-900 sm:text-5xl">Intelligent energy control</h2>
          </div>

          {/* Icon strip */}
          <div className="mb-12 grid gap-6 sm:grid-cols-3">
            {benefits.map((benefit) => {
              const Icon = benefit.icon;
              return (
                <div key={benefit.title} className="flex items-center gap-4">
                  <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-[#6D39B5]/10">
                    <Icon className="h-6 w-6 text-[#6D39B5]" />
                  </div>
                  <div>
                    <p className="font-medium text-stone-900">{benefit.title}</p>
                    <p className="text-sm text-stone-500">{benefit.description}</p>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Large feature image with purple glow */}
          <div className="relative">
            <div className="absolute -inset-4 rounded-3xl bg-[#6D39B5]/15 blur-3xl" />
            <div className="relative overflow-hidden rounded-2xl shadow-[0_30px_80px_-25px_rgba(109,57,181,0.35)]">
              <img
                src="/assets/microinverters/intelligent-energy-control.webp"
                alt="Rooftop solar array with microinverters"
                className="aspect-[21/9] w-full object-cover"
                loading="lazy"
                decoding="async"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Fit Scenarios — Staggered layout with large images */}
      <section className="bg-[linear-gradient(145deg,#6d5a96_0%,#836fb0_52%,#9a86c2_100%)] py-16 text-white sm:py-24">
        <div className="mx-auto max-w-[1400px] px-6 sm:px-8">
          <div className="mb-12 max-w-2xl">
            <p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-white/50">DESIGN CONSIDERATIONS</p>
            <h2 className=" text-4xl leading-tight sm:text-5xl">Choosing the right configuration</h2>
          </div>

          <div className="space-y-16">
            {fitScenarios.map((scenario, i) => (
              <div key={scenario.title} className={`grid gap-8 items-center lg:grid-cols-2 ${i % 2 === 1 ? 'lg:flex-row-reverse' : ''}`}>
                <div className={i % 2 === 1 ? 'lg:order-2' : ''}>
                  <div className="relative overflow-hidden rounded-2xl shadow-[0_25px_60px_-20px_rgba(109,57,181,0.4)]">
                    <img
                      src={scenario.image}
                      alt={scenario.title}
                      className="aspect-[16/10] w-full object-cover"
                      loading="lazy"
                      decoding="async"
                    />
                  </div>
                </div>
                <div className={i % 2 === 1 ? 'lg:order-1 lg:pr-12' : 'lg:pl-12'}>
                  <span className="text-xs font-mono text-[#8553c2]">0{i + 1}</span>
                  <h3 className="mt-2  text-3xl text-white sm:text-4xl">{scenario.title}</h3>
                  <p className="mt-3 text-lg text-white/60">{scenario.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Engineering First — Compact text card over image corner */}
      <section className="py-16 sm:py-24">
        <div className="mx-auto max-w-[1400px] px-6 sm:px-8">
          <div className="relative">
            <div className="relative overflow-hidden rounded-2xl shadow-[0_30px_80px_-25px_rgba(109,57,181,0.3)] lg:rounded-3xl">
              <img
                src="/assets/microinverters/no-one-size-fits-all.webp"
                alt="Solar installer at work"
                className="h-[450px] w-full object-cover sm:h-[550px]"
                loading="lazy"
                decoding="async"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/40 to-transparent" />
            </div>

            {/* Floating card */}
            <div className="relative mt-6 rounded-xl bg-white p-6 shadow-xl sm:mt-8 sm:p-8 xl:absolute xl:bottom-10 xl:left-10 xl:mt-0 xl:max-w-sm xl:rounded-2xl">
              <p className="mb-3 text-xs font-semibold uppercase tracking-[0.16em] text-[#6D39B5]">ENGINEERING FIRST</p>
              <h3 className="mb-3  text-2xl text-stone-900">No one-size-fits-all</h3>
              <p className="text-stone-600 leading-relaxed">
                We evaluate multiple inverter configurations against your roof layout, shading conditions, electrical infrastructure, and long-term plans - then walk you through the performance and scalability tradeoffs.
              </p>
              <a href="#contact" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-[#6D39B5]">
                Design My System
                <ArrowRight className="h-4 w-4" />
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ — unchanged */}
      <section className="bg-white py-16 sm:py-20">
        <div className="mx-auto max-w-[980px] px-6 sm:px-8">
          <h2 className=" text-4xl text-stone-900 sm:text-5xl">Frequently Asked Questions</h2>
          <Accordion type="single" collapsible className="mt-8 rounded-2xl border border-gray-200 bg-white px-6">
            {faqs.map((faq, index) => (
              <AccordionItem key={faq.q} value={`faq-${index}`}>
                <AccordionTrigger className="text-left text-lg text-[#231f2a]">{faq.q}</AccordionTrigger>
                <AccordionContent className="text-base text-gray-600">{faq.a}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      <GlobalQuoteSection />
      <Footer />
    </main>
  );
};

export default Microinverters;
